version: "3.9"

services:
  event-bus:
    build: ./event-bus
    ports:
      - "4005:4005"

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "4001:4001"
    depends_on:
      - event-bus

  order-service:
    build: ./order-service
    ports:
      - "4002:4002"
    env_file:
      - ./order-service/.env
    depends_on:
      - event-bus

  delivery-service:
    build: ./delivery-service
    ports:
      - "4003:4003"
    depends_on:
      - event-bus
      - order-service

  notification-service:
    build: ./notification-service
    ports:
      - "4004:4004"
    depends_on:
      - event-bus

  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - restaurant-service
      - order-service
